### ISSUE TITLE
[question]: Why yet creating another library?

### ISSUE THREAD

**Issue by norkunas** [OneSignal/onesignal-php-api#13]
### How can we help?

I've maintaining https://github.com/norkunas/onesignal-php-api since 2015 which is modern, has tests and more than 1m downloads. I'd be gladly transfered it under OneSignal ownership, but yet here we are, with a library that does not use at least [PSR HttpClient](https://www.php-fig.org/psr/psr-18/) and ties the consumers to the guzzle library instead of giving them choice to use any. :slightly_smiling_face: 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @norkunas! Thanks for your contribution, we really appreciate your effort in this direction!
At the moment our approach for building these server API libraries is to generate them from the OpenAPI [schema](https://github.com/OneSignal/api) using our private fork of [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator).
As you can see here, currently we have 9 [libraries](https://github.com/OpenAPITools/openapi-generator) all generated from the same source. 
It worth mentioning that we constantly update the schema with new endpoints, fixes, documentation etc. It's just not feasible for us to maintain so many code sources separately.
We understand that provided implementation may not be the best for all the language, but that's what OpenAPI generator provides. At least we can guarantee that it stays up to date with the OneSignal official API in most cases. 
Honestly I don't know what to suggest here. Your library seems to be more user friendly and idiomatic then the one we provide, but it's not covering all the functions and method we have in our API.
We would appreciate if you add a link to the official OneSignal PHP library in your repo.
Thanks again, and sorry for this confusion!

**Comment by norkunas** [comment]
Maybe you could try to use https://github.com/janephp/janephp which is supports PSR18 :)
