### ISSUE TITLE
[question]: App Key Token = Rest API Key?

### ISSUE THREAD

**Issue by kodie** [OneSignal/onesignal-php-api#16]
### How can we help?

I'm just getting started with OneSignal and the PHP SDK, I don't see anything in the OneGuide documentation about an "App Key Token". I'm assuming this is the "Rest API Key" found in the "Keys & IDs" section of the dashboard?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@kodie Yes that is correct is that key not working for you?

**Comment by kodie** [comment]
@emawby I haven't had a chance to try it yet. Still awaiting on Apple's approval process 🙄 just wanted to get all my ducks in a row. Thanks!

**Comment by kodie** [comment]
@emawby Just confirming that this indeed is working fine for me. Thanks!
